[build-system]
requires = ["setuptools>=76.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "torrent-directories"
version = "1.4.3"
description = "A tool for creating torrent files from directories"
requires-python = ">=3.12"
authors = [
    { name = "friedhardware" },
]
dependencies = [
    "libtorrent>=2.0.0",
    "click>=8.1.3",
]

[project.optional-dependencies]
dev = [
    "setuptools>=76.0.0",
    "pytest>=8.0.0",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "click>=8.1.3",
]

[project.scripts]
torrent-directories = "torrent.cli.__main__:main"

[tool.black]
line-length = 88
target-version = ["py312"]
include = '\.pyi?$'

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.ruff]
line-length = 88
target-version = "py312"
